language: c

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

os:
    - linux
    - osx

env:
  global:
    - SETUP_XVFB=True
    - CONDA_DEPENDENCIES="pytest matplotlib nose coverage"
    - PIP_DEPENDENCIES="pytest-cov coveralls"
  matrix:
    - PYTHON_VERSION=2.6 MATPLOTLIB_VERSION=1.4 NUMPY_VERSION=1.9
    - PYTHON_VERSION=2.7 MATPLOTLIB_VERSION=1.4 NUMPY_VERSION=1.9
    - PYTHON_VERSION=3.3 MATPLOTLIB_VERSION=1.4 NUMPY_VERSION=1.9
    - PYTHON_VERSION=3.4 MATPLOTLIB_VERSION=1.4 NUMPY_VERSION=1.9
    - PYTHON_VERSION=2.7 MATPLOTLIB_VERSION=1.5
    - PYTHON_VERSION=3.5 MATPLOTLIB_VERSION=1.5
    - PYTHON_VERSION=2.7 MATPLOTLIB_VERSION=2.0 CONDA_CHANNELS="conda-forge/label/rc conda-forge"
    - PYTHON_VERSION=3.5 MATPLOTLIB_VERSION=2.0 CONDA_CHANNELS="conda-forge/label/rc conda-forge"

install:

    # We use the ci-helpers package from the Astropy project to set up conda
    # with any requested dependencies above.
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh

    # Need to use develop instead of install to make sure coverage works
    - python setup.py develop

script:
   - python -c 'import pytest_mpl.plugin'
   - py.test --mpl --cov pytest_mpl tests
   - if [[ $PYTHON_VERSION != 2.6 ]]; then python setup.py check --restructuredtext; fi

after_success:
   - coveralls
