name: Run tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
        # Test the oldest and newest configuration on Mac and Windows
        - os: macos-latest
          python-version: 3.6
          toxenv: py36-test-mpl20
        - os: macos-latest
          python-version: 3.8
          toxenv: py36-test-mpl31
        - os: windows-latest
          python-version: 3.6
          toxenv: py36-test-mpl20
        - os: windows-latest
          python-version: 3.8
          toxenv: py36-test-mpl31
        # Test all configurations on Linux
        - os: ubuntu-latest
          python-version: 3.6
          toxenv: py36-test-mpl20
        - os: ubuntu-latest
          python-version: 3.6
          toxenv: py36-test-mpl21
        - os: ubuntu-latest
          python-version: 3.6
          toxenv: py36-test-mpl22
        - os: ubuntu-latest
          python-version: 3.7
          toxenv: py37-test-mpl30
        - os: ubuntu-latest
          python-version: 3.8
          toxenv: py38-test-mpl31
        # Code style checks
        - os: ubuntu-latest
          python-version: 3.8
          toxenv: codestyle

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: python -m pip install tox
    - name: Run tox
      run: python -m tox -e  ${{ matrix.toxenv }}



